import About from 'components/About';
import Contact from 'components/Contact';
import Main from 'components/Main';
import Navbar from 'components/Navbar';
import Reviews from 'components/Reviews';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Репетитор Надежда Кузнецова</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Reviews />
      <Contact />
    </>
  );
}
